#ifndef ASSEMBLERPERSONAL_CONVERTTOBASEFOUR_H
#define ASSEMBLERPERSONAL_CONVERTTOBASEFOUR_H

int encrypt(char *file_name);
char* convertToBaseFour(const char *str);

#endif //ASSEMBLERPERSONAL_CONVERTTOBASEFOUR_H