# Compiler
CC = gcc

# Compiler flags
CFLAGS = -ansi -Wall -pedantic -g # Flags for debugging

# Source files
SOURCES = $(wildcard SourceFiles/*.c)

# Object files
OBJECTS = $(SOURCES:.c=.o)

# Executable name
EXECUTABLE = AssemblerPersonal

# Rule for making the final executable
$(EXECUTABLE): $(OBJECTS)
	$(CC) $(CFLAGS) -o $@ $^

# Rule for making the object files
%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

# Phony target for cleaning the build
.PHONY: clean
clean:
	rm -f $(OBJECTS) $(EXECUTABLE) *.am *.ob *.ent *.ext